// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ProjectContentImageMulti: typeof import('./components/Project/Content/ProjectContentImageMulti.vue')['default']
    ProjectContentMedia: typeof import('./components/Project/Content/ProjectContentMedia.vue')['default']
    ProjectContentMediaGallery: typeof import('./components/Project/Content/ProjectContentMediaGallery.vue')['default']
    ProjectContentMediaText: typeof import('./components/Project/Content/ProjectContentMediaText.vue')['default']
    ProjectContentThree: typeof import('./components/Project/Content/ProjectContentThree.vue')['default']
    ProjectContentVideo: typeof import('./components/Project/Content/ProjectContentVideo.vue')['default']
    ProjectListHeader: typeof import('./components/Project/ProjectListHeader.vue')['default']
    ProjectMetadata: typeof import('./components/Project/ProjectMetadata.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}

export { }
