// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    BackButton: typeof import('./components/BackButton.vue')['default']
    LoadingBar: typeof import('./components/LoadingBar.vue')['default']
    ProjectContentMedia: typeof import('./components/project/content/ProjectContentMedia.vue')['default']
    ProjectContentMediaGallery: typeof import('./components/project/content/ProjectContentMediaGallery.vue')['default']
    ProjectContentMediaText: typeof import('./components/project/content/ProjectContentMediaText.vue')['default']
    ProjectContentSectionHeader: typeof import('./components/project/content/ProjectContentSectionHeader.vue')['default']
    ProjectContentThree: typeof import('./components/project/content/ProjectContentThree.vue')['default']
    ProjectContentVideo: typeof import('./components/project/content/ProjectContentVideo.vue')['default']
    ProjectDescription: typeof import('./components/project/content/ProjectDescription.vue')['default']
    ProjectListHeader: typeof import('./components/project/ProjectListHeader.vue')['default']
    ProjectMetadata: typeof import('./components/project/ProjectMetadata.vue')['default']
    ProjectModels: typeof import('./components/ProjectModels.vue')['default']
    TextSplitter: typeof import('./components/TextSplitter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}

export { }
